language: node_js
node_js:
- 10.16.0
cache: npm 

install:
- npm install

script:
- npm start

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  
  on: 
    branch: master

